CREATE TABLE FAMILIA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FAMILIA NVARCHAR(50) NOT NULL
);

INSERT INTO FAMILIA (FAMILIA) VALUES ('Chapa');
INSERT INTO FAMILIA (FAMILIA) VALUES ('Tubo');
INSERT INTO FAMILIA (FAMILIA) VALUES ('Plástico');

------------------------------------------------------
CREATE TABLE SUBFAMILIA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FAMILIA NVARCHAR(50) NOT NULL,
    SUBFAMILIA NVARCHAR(50) NOT NULL
);

INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Inox');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Aço');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Aluminio');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Tubo', 'Galvonizado');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Tubo', 'Inox');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PET');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PVC');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PP');
------------------------------------------------------
CREATE TABLE MATERIAL (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CODIGO INT,
    DESCRICAO NVARCHAR(100) NOT NULL,
    FAMILIA NVARCHAR(50) NOT NULL,
    SUBFAMILIA NVARCHAR(50) NOT NULL,
    UNIDADE_DE_MEDIDA NVARCHAR(30) NOT NULL,
);