CREATE TABLE MATERIAL (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CODIGO INT,
    DESCRICAO NVARCHAR(100) NOT NULL,
    FAMILIA NVARCHAR(50) NOT NULL,
    SUBFAMILIA NVARCHAR(50) NOT NULL,
    UNIDADE_DE_MEDIDA NVARCHAR(30) NOT NULL,
);