CREATE TABLE SUBFAMILIA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FAMILIA NVARCHAR(50) NOT NULL,
    SUBFAMILIA NVARCHAR(50) NOT NULL
);

INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Inox');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Aço');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Chapa', 'Aluminio');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Tubo', 'Galvonizado');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Tubo', 'Inox');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PET');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PVC');
INSERT INTO SUBFAMILIA (FAMILIA, SUBFAMILIA) VALUES ('Plástico', 'PP');